POST http://localhost:3000/posts/
Content-Type: application/json

{
  "title": "title post test",
  "postType": "post",
  "slug": "new-with-nestjs-2",
  "status": "published",
  "content": "learning nestjs",
  "schema": "schema test",
  "imageUrl": "https://abc.com",
  // "tags": ["nestjs", "js"],
  "publishDate": "2023-11-14T09:45:00Z",
  "metaOptions": {
    "metaValue":  "{\"key\": key1, \"value\": value1 }"
  }
}