POST http://localhost:3000/posts/
Content-Type: application/json

{
  "title": "namdz111",
  "postType": "post",
  "slug": "namdz111",
  "status": "published",
  "content": "learning nestjs",
  "schema": "schema test",
  "imageUrl": "https://abc.com",
  // "tags": ["nestjs", "js"],
  "publishDate": "2023-11-14T09:45:00Z",
  "metaOptions": {
    "metaValue":  "{\"key\": key1, \"value\": value1 }"
  },
  "authorId": 1,
  "tags": [7]
}