POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "do nam",
  "email": "nam@gmail.com",
  "password": "1a23456",
  "id": "1"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json

{
  "users": [
    {
      "firstName": "do nam22",
      "email": "okok@gmail.com",
      "password": "1a23456",
      "age": 10
    },
    {
      "firstName": "do nam11",
      "email": "111okok@gmail.com",
      "password": "1a23456",
      "age": 11
    }
  ]
}
